### PR TITLE
call the tracing agent CLI for executing client functions

### LINKED ISSUE #69: From Identity Server Call Tracing Agent's CLI to Execution Functions And Tests
### Summary

Identity Server Version: `1.0.5`
Identity Server is incorrectly configured to call the client app. It should call the CLI to execute functions and tests 

`python -m identity_trace ....`

### PR DESCRIPTION
**Pull request by MamoonAhmad**
Closes #69 

### Major Version
Although we are changing the functionality of config file, we dont need to change the major version as we dont have any users yet :(

### CODE REVIEW

File: identity-server/backend/entities/UserSetting/validator.js [hunk 1]
```diff
@@ -16,6 +16,15 @@ export const validateUserSetting = (userSettings) => {
         throwError(ERROR_CODES.VALIDATION_ERROR, { ...defaultErrorMeta, field: "server_port", extraMessage: " server_port should be an integer value." })
     }
 
+    // Python Path is required
+    if(!userSettings.python_path) {
```
Comment (MamoonAhmad) [inline identity-server/backend/entities/UserSetting/validator.js:20]: This would normally require us to change the major version.
